### ISSUE TITLE
Pod update fail

### ISSUE THREAD

**Issue by SummerTree** [heyalexchoi/Giphy-iOS#1]
I think you can change the pod spec url from git@github.com:heyalexchoi/Giphy-iOS.git to https://github.com/heyalexchoi/Giphy-iOS.git, or people use you lib will get the fallowing error while installing the pod

[!] /usr/bin/git clone git@github.com:heyalexchoi/Giphy-iOS.git /Users/liyipeng/Library/Caches/CocoaPods/GitHub/6c18fae873774676144b1767c5a5be1f87355cad --mirror

Cloning into bare repository '/Users/liyipeng/Library/Caches/CocoaPods/GitHub/6c18fae873774676144b1767c5a5be1f87355cad'...

Permission denied (publickey).

thanks

**Comment by heyalexchoi** [comment]
Giphy-iOS now uses https git source
